perf(core): disable lastLogin update as an option
vendurehq/vendure pull request #3253
Opened 2024-12-02 11:05 UTC by alexisvigoureux

# Description

Disable the last login update (prevent a save on user entity) when a user logs in.

# Breaking changes
No

# Screenshots

context: our users need to be authenticated to view our products.
We receive a lots of request on the authenticate endpoint, and we have a bottleneck on this endpoint.

When we have too much traffic, we have locks on the ‘user’ table

<img width="1311" alt="Capture d’écran 2024-11-29 à 15 47 49" src="https://github.com/user-attachments/assets/f6965dec-04ef-4743-95fa-70f82e652b8b">

<img width="1080" alt="Capture d’écran 2024-11-29 à 15 48 16" src="https://github.com/user-attachments/assets/1b464955-ce34-4419-a4df-3c33c8925b4f">

Here is the request `UPDATE "user" SET "lastLogin" = $1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" IN ($2)`
This query is not useful for us. This PR proposes a solution to deactivate it and avoid a lock on the user table.
In terms of volume, this represents more than 250k updates of the lastLogin field per day, often at the same connection time.

Not sure where to write the tests, please let me know. 

# Checklist

📌 Always:
- [x] I have set a clear title
- [x] My PR is small and contains a single feature
- [x] I have [checked my own PR](## "Fix typo's and remove unused or commented out code")

👍 Most of the time:
- [ ] I have added or updated test cases
- [ ] I have updated the README if needed

2025-03-24 20:31 UTC, DanielBiegler commented on packages/core/src/service/services/auth.service.ts
> +        }
```suggestion
        if (!this.configService.authOptions.disableLastLoginUpdate) {
            user.lastLogin = new Date();
            await this.connection.getRepository(ctx, User).save(user, { reload: false });
        }
```

I'm curious, why include `user.roles` in the condition? Especially if it specifically gets set above, doesnt that result in this always being cast to `true` since even empty arrays are `true` ?

2025-06-20 12:19 UTC, dlhck requested changes
Thank you. Please see my comments. This could go into `v3.4.0`, so please also change the target to `minor`

2025-06-20 12:19 UTC, dlhck commented on packages/core/src/service/services/auth.service.ts
> +        }
@alexisvigoureux could we please remove the `user.roles` condition? I think it is not necessary. If that's a way how do differentiate between a customer and an administrator, we should do it differently.

2025-06-20 12:19 UTC, dlhck commented on packages/core/src/config/vendure-config.ts
> +     * @since 3.0.7
We should use `v3.4.0` here

2026-08-25 15:23 UTC, biggamesmallworld commented
Closing in favor of a fresh take-over PR that rebases this onto current `minor`, applies the review feedback (drop the `user.roles` condition, correct `@since`), and adds coverage.

Thank you @alexisvigoureux for the original work and for documenting the user-table lock contention under high auth traffic — you'll be credited as the original author on the replacement PR.

2026-08-25 15:23 UTC, closed without merging

2026-08-25 15:25 UTC, biggamesmallworld commented
Replacement PR: https://github.com/vendurehq/vendure/pull/5184

2026-08-25 15:31 UTC, biggamesmallworld commented
Replacement PR: https://github.com/vendurehq/vendure/pull/5184

2026-08-25 16:30 UTC, biggamesmallworld commented
Replacement PR: https://github.com/vendurehq/vendure/pull/5184

2026-08-25 17:27 UTC, biggamesmallworld commented
Replacement PR: https://github.com/vendurehq/vendure/pull/5184

2026-08-25 18:12 UTC, biggamesmallworld commented
Replacement PR: https://github.com/vendurehq/vendure/pull/5184